config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#index', as: 'welcome'
  post 'send_array', to: 'application#get_array', as: 'send_array'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def get_array
    @var=params[:items].reject(&:blank?)
    @j=0
    @i=0
    @counter=0
    @ok=0
    for @j in 0..@var.length-1 do
      while (@i<(@var.length-1)) && (@ok<@var.length-2)
        if @i==@j
          @i=@i+1
        end
        if @j==@i+1
          @t=@i+2
        else
          @t=@i+1
        end
        if(@var[@i].to_i<=@var[@t].to_i)
          @i+=1
          @ok+=1
        else
          break
        end
      end
      if @ok==@var.length-2
        @counter+=1
      end
      @j+=1
      @i=0
      @ok=0
    end
    render :results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_items_form.html.erb
<div class="container text-center">
    <div style="margin-top: 1%; margin-bottom: 1%" class="form-group col-md-12 row text-center">
      <div class="col-md-3"></div>
      <label class="col-md-2 control-label">Plant's height:</label>
      <input type="number" name="items[]" id="items_" min="0" step="1" class="form-control col-md-2" >
    </div>
</div>

app/views/application/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plant Test</title>
  </head>
  <body>
  <div class="container text-center col-md-8">
    <div class="jombotron shadow p-3 mb-5 bg-white rounded" style="margin-top: 15%">
      <%= form_for :plants, url:send_array_path do |f| %>
        <div id="plantSet">
          <a href="javascript:;" id="addNewItem">Add New Plant</a>
          <%= render partial: "items_form" %>
        </div>
        <div class="actions">
          <%= f.submit "Results", class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="hide" id="new_items_form">
    <%= render partial: "items_form", locals: {skill: false} %>
  </div>
  </body>
</html>

app/views/application/results.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plant Test</title>
</head>
  <body>
  <div class="container text-center">
    <div class="jombotron shadow p-3 mb-5 bg-white rounded" style="margin-top: 5%">

      <table border="1" class="table table-striped">
        <thead>
        <tr>
          <% @var.each do |item| %>
            <th><%= item %></th>
          <% end %>
        </tr>
        </thead>
      </table>
      <div> You can remove <h3 class="red"><%= @counter %></h3> plants and the rest would still be in non-descending order!</div>
      <div class="col-md-3"></div><div><%= button_to 'Back', welcome_path, method: :get, class: "btn btn-info" %></div>
    </div>
  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>